# Generated by Django 2.2 on 2019-04-19 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessories_id_list', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Accessory',
                'verbose_name_plural': 'Accessories',
            },
        ),
        migrations.CreateModel(
            name='Analog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analog_id_list', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Analog',
                'verbose_name_plural': 'Analogs',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Published date')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_USD', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cur_EUR', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cur_UAH', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'verbose_name': 'Currency',
                'ordering': ['-cur_USD'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['-department_name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufac_name', models.CharField(db_index=True, max_length=50, verbose_name='Manufacturer name')),
                ('manufac_country', models.CharField(max_length=60, verbose_name='Country')),
                ('manufac_city', models.CharField(max_length=60, verbose_name='City')),
                ('manufac_address', models.CharField(max_length=150, verbose_name='Address')),
                ('manufac_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('manufac_phone', models.CharField(max_length=65, verbose_name='Contact phone')),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
                'ordering': ['-manufac_name'],
            },
        ),
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_title', models.CharField(max_length=50, verbose_name='Product name')),
                ('prod_img', models.ImageField(blank=True, null=True, upload_to='prod_photos/%Y/%m/%D/', verbose_name='Product image')),
                ('prod_description', models.TextField(blank=True, null=True, verbose_name='Product description')),
                ('prod_materials', models.CharField(blank=True, max_length=250, null=True, verbose_name='Made of')),
                ('prod_year', models.CharField(blank=True, max_length=4, null=True)),
                ('prod_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prod_availability', models.BooleanField(default=True, null=True)),
                ('prod_rate', models.IntegerField(blank=True, null=True, verbose_name='Rate')),
                ('prod_accessories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Accessories', verbose_name='Accessories')),
                ('prod_analog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Analog', verbose_name='Analog')),
                ('prod_comments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Comments', verbose_name='Comments')),
                ('prod_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.Currency', verbose_name='Currency')),
                ('prod_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Department', verbose_name='Department')),
                ('prod_manufacturer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Manufacturer', verbose_name='Manufacturer')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-prod_title'],
            },
        ),
    ]
