# Generated by Django 2.2 on 2019-04-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190420_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='prod_currency',
            new_name='prod_currency_info',
        ),
        migrations.AlterField(
            model_name='store',
            name='prod_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Rate'),
        ),
    ]
