# Generated by Django 2.2 on 2019-04-20 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20190420_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='manufac_site',
            field=models.URLField(blank=True, null=True, verbose_name='Web-site'),
        ),
        migrations.AlterField(
            model_name='store',
            name='prod_currency_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Currency', verbose_name=' Current currency'),
        ),
    ]
