# Generated by Django 2.2 on 2019-04-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20190420_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='manufac_type',
            field=models.CharField(blank=True, choices=[('g', 'guitars'), ('d', 'drums'), ('k', 'keyboards'), ('a', 'all')], max_length=20, null=True, verbose_name='Type'),
        ),
    ]
