# Generated by Django 2.2 on 2019-04-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_manufacturer_manufac_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='prod_type',
            field=models.CharField(blank=True, choices=[('g', 'guitars'), ('d', 'drums'), ('k', 'keyboards'), ('a', 'all')], max_length=20, null=True, verbose_name='Type'),
        ),
    ]
