# Generated by Django 2.2 on 2019-04-20 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20190420_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='prod_type',
            field=models.CharField(blank=True, choices=[('ag', 'acoustic guitar'), ('eg', 'electric guitar')], max_length=20, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='store',
            name='prod_analog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Analog', verbose_name='Analog'),
        ),
    ]
