# Generated by Django 2.2 on 2019-04-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20190420_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='manufac_type',
            field=models.CharField(blank=True, choices=[('g', 'guitars'), ('d', 'drums'), ('k', 'keyboards'), ('u', 'ukulele'), ('a', 'all')], max_length=20, null=True, verbose_name='Type'),
        ),
    ]
