# Generated by Django 2.2 on 2019-04-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20190420_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='prod_type',
            field=models.CharField(blank=True, choices=[('ag', 'acoustic guitar'), ('eg', 'electric guitar'), ('uk', 'ukulele')], max_length=20, null=True, verbose_name='Type'),
        ),
    ]
