# Generated by Django 2.2 on 2019-04-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20190420_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='cur_EUR',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='currency',
            name='cur_RUB',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='currency',
            name='cur_USD',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=12),
        ),
    ]
