# Generated by Django 2.2 on 2019-04-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20190420_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='manufac_name',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Company name'),
        ),
    ]
