# Generated by Django 2.2 on 2019-04-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20190420_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Published date'),
        ),
    ]
