# Generated by Django 2.2 on 2019-04-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20190421_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-published_date'], 'verbose_name': 'Currency', 'verbose_name_plural': 'Currency'},
        ),
        migrations.RemoveField(
            model_name='store',
            name='prod_price',
        ),
        migrations.AddField(
            model_name='store',
            name='prod_origin_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Original price'),
        ),
    ]
