# Generated by Django 2.2 on 2019-04-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20190421_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='manufac_type',
            field=models.CharField(blank=True, choices=[('g', 'guitars'), ('d', 'drums'), ('k', 'keyboards'), ('u', 'ukulele'), ('m', 'mics'), ('a', 'all')], max_length=20, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='store',
            name='prod_type',
            field=models.CharField(blank=True, choices=[('ag', 'acoustic guitar'), ('eg', 'electric guitar'), ('uk', 'ukulele'), ('mic', 'mics'), ('keyb', 'keyboards'), ('drm', 'drums'), ('acc', 'accessories')], max_length=20, null=True, verbose_name='Type'),
        ),
    ]
