# Generated by Django 2.2 on 2019-04-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20190421_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['pk'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='store',
            name='prod_url',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Product_URL'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='manufac_type',
            field=models.CharField(blank=True, choices=[('g', 'guitars'), ('d', 'drums'), ('k', 'keyboards'), ('u', 'ukulele'), ('m', 'mics'), ('s', 'sound insulation'), ('a', 'all')], max_length=20, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='store',
            name='prod_img',
            field=models.ImageField(blank=True, null=True, upload_to='prod_photos/', verbose_name='Product image'),
        ),
        migrations.AlterField(
            model_name='store',
            name='prod_type',
            field=models.CharField(blank=True, choices=[('Акустическая гитара', 'acoustic guitar'), ('Электрогитара', 'electric guitar'), ('Укулеле', 'ukulele'), ('Микрофон', 'mics'), ('Синтезакоры', 'keyboards'), ('Барабаны', 'drums'), ('Аксессуары', 'accessories'), ('Звукоизоляция', 'sound insulation')], max_length=20, null=True, verbose_name='Type'),
        ),
    ]
