# Generated by Django 2.2 on 2019-04-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20190424_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='prod_updated_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Original price'),
        ),
    ]
