# Generated by Django 2.2 on 2019-04-24 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20190424_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='prod_score_likes',
            new_name='prod_rate',
        ),
        migrations.RemoveField(
            model_name='store',
            name='prod_score_dislikes',
        ),
    ]
