# Generated by Django 2.2 on 2019-04-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20190424_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='prod_counter',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='store',
            name='prod_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rate'),
        ),
    ]
