# Generated by Django 2.2 on 2019-04-24 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20190424_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='prod_comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Store', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='store',
            name='prod_counter',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Rate counter'),
        ),
    ]
