# Generated by Django 2.2 on 2019-04-24 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20190425_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Store', verbose_name='Product'),
        ),
    ]
