# Generated by Django 2.2 on 2019-04-24 23:52

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20190425_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_first_name', models.CharField(max_length=50, verbose_name='Name')),
                ('cust_last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Second name')),
                ('cust_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Address')),
                ('cust_phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('cust_email', models.EmailField(max_length=150, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['pk'],
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='store',
            name='prod_accessories',
        ),
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Store', verbose_name='Product'),
        ),
    ]
